name: Simple deploy using ssh and git pull

on:
  push:
    branches:
      - master
      - github-ci-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/deploy/concierge
            git pull
            (cd server && npm i && pm2 restart concierge_server)
            (cd client && npm i && npm run build)
            echo "fin"
